import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/header/header'
import { Providers } from './providers'
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={GeistMono.className}>
        <Providers>
          <Header />
          <div className="absolute top-0 z-[-2] h-screen w-screen dark:bg-[#000000] dark:bg-[radial-gradient(#ffffff33_1px,#080808_1px)] bg-[size:20px_20px]"></div>
          <div class="absolute inset-0 -z-10 h-full w-full bg-white bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px]"></div>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
