import { NextResponse } from 'next/server'

const tableData = [
  {
    id: 'm5gr84i1',
    status: 'success',
    email: 'ana@edge.ufal.br',
    name: 'Ana Silva',
    class: '1',
  },
  {
    id: 'm5gr84i2',
    status: 'success',
    email: 'rodrigo@edge.ufal.br',
    name: 'Rodrigo Santos',
    class: '1',
  },
  {
    id: 'm5gr84i3',
    status: 'pending',
    email: 'maria@edge.ufal.br',
    name: 'Maria Oliveira',
    class: '1',
  },
  {
    id: 'm5gr84i4',
    status: 'success',
    email: 'lucas@edge.ufal.br',
    name: 'Lucas Pereira',
    class: '1',
  },
  {
    id: 'm5gr84i5',
    status: 'failed',
    email: 'carol@edge.ufal.br',
    name: 'Carol Souza',
    class: '1',
  },
  {
    id: 'm5gr84i6',
    status: 'success',
    email: 'rafael@edge.ufal.br',
    name: 'Rafael Lima',
    class: '2',
  },
  {
    id: 'm5gr84i7',
    status: 'success',
    email: 'julia@edge.ufal.br',
    name: 'Júlia Costa',
    class: '3',
  },
  {
    id: 'm5gr84i8',
    status: 'pending',
    email: 'gabriel@edge.ufal.br',
    name: 'Gabriel Oliveira',
    class: '4',
  },
  {
    id: 'm5gr84i9',
    status: 'success',
    email: 'ken@edge.ufal.br',
    name: 'Ken Silva',
    class: '2',
  },
  {
    id: 'm5gr84i10',
    status: 'failed',
    email: 'camila@edge.ufal.br',
    name: 'Camila Santos',
    class: '2',
  },
  {
    id: 'm5gr84i11',
    status: 'success',
    email: 'felipe@edge.ufal.br',
    name: 'Felipe Oliveira',
    class: '2',
  },
  {
    id: 'm5gr84i12',
    status: 'pending',
    email: 'isabela@edge.ufal.br',
    name: 'Isabela Silva',
    class: '4',
  },
  {
    id: 'm5gr84i13',
    status: 'success',
    email: 'pedro@edge.ufal.br',
    name: 'Pedro Santos',
    class: '3',
  },
  {
    id: 'm5gr84i14',
    status: 'failed',
    email: 'lara@edge.ufal.br',
    name: 'Lara Oliveira',
    class: '3',
  },
  {
    id: 'm5gr84i15',
    status: 'success',
    email: 'vinicius@edge.ufal.br',
    name: 'Vinícius Costa',
    class: '1',
  },
  {
    id: 'm5gr84i16',
    status: 'success',
    email: 'clara@edge.ufal.br',
    name: 'Clara Santos',
    class: '1',
  },
  {
    id: 'm5gr84i17',
    status: 'pending',
    email: 'leonardo@edge.ufal.br',
    name: 'Leonardo Oliveira',
    class: '2',
  },
  {
    id: 'm5gr84i18',
    status: 'success',
    email: 'mariana@edge.ufal.br',
    name: 'Mariana Silva',
    class: '2',
  },
  {
    id: 'm5gr84i19',
    status: 'failed',
    email: 'gustavo@edge.ufal.br',
    name: 'Gustavo Costa',
    class: '3',
  },
  {
    id: 'm5gr84i20',
    status: 'success',
    email: 'lucia@edge.ufal.br',
    name: 'Lúcia Oliveira',
    class: '3',
  },
  {
    id: 'm5gr84i21',
    status: 'failed',
    email: 'paulo@edge.ufal.br',
    name: 'Paulo Silva',
    class: '4',
  },
  {
    id: 'm5gr84i22',
    status: 'success',
    email: 'natalia@edge.ufal.br',
    name: 'Natália Costa',
    class: '1',
  },
  {
    id: 'm5gr84i23',
    status: 'success',
    email: 'thiago@edge.ufal.br',
    name: 'Thiago Santos',
    class: '2',
  },
  {
    id: 'm5gr84i24',
    status: 'pending',
    email: 'alice@edge.ufal.br',
    name: 'Alice Silva',
    class: '4',
  },
  {
    id: 'm5gr84i25',
    status: 'success',
    email: 'marcos@edge.ufal.br',
    name: 'Marcos Oliveira',
    class: '3',
  },
  {
    id: 'm5gr84i26',
    status: 'failed',
    email: 'caroline@edge.ufal.br',
    name: 'Caroline Santos',
    class: '1',
  },
  {
    id: 'm5gr84i27',
    status: 'success',
    email: 'leonel@edge.ufal.br',
    name: 'Leonel Costa',
    class: '2',
  },
  {
    id: 'm5gr84i28',
    status: 'pending',
    email: 'amanda@edge.ufal.br',
    name: 'Amanda Silva',
    class: '3',
  },
  {
    id: 'm5gr84i29',
    status: 'success',
    email: 'bruno@edge.ufal.br',
    name: 'Bruno Oliveira',
    class: '4',
  },
]

export const GET = async () => {
  return NextResponse.json({
    tableData,
  })
}
